<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\NetQuestion.Contracts\NetQuestion.Contracts.csproj" />
      <ProjectReference Include="..\NetQuestions.Entity\NetQuestions.Entity.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" />
    </ItemGroup>

</Project>
